### ISSUE TITLE
Jetpack 2.9.3: Critical Security Update

### ISSUE THREAD

**Issue by Dave-Parker** [leomeih/slimjp#5]
Is this plugin affected by this? http://jetpack.me/2014/04/10/jetpack-security-update/

If so, can you please update Slim Jetpack to fix it?

Thanks!

**Comment by leomeih** [comment]
I checked the latest commit history of Jetpack and didn't find anything related to slimjetpack, which contains mostly offline modules.
Anyway, I decided to update the code here for maintenance purpose.
